// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.4
// source: widgets/widgets.proto

package widgetsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WidgetType int32

const (
	WidgetType_NULL   WidgetType = 0
	WidgetType_Custom WidgetType = 1
	WidgetType_Cc     WidgetType = 2
)

// Enum value maps for WidgetType.
var (
	WidgetType_name = map[int32]string{
		0: "NULL",
		1: "Custom",
		2: "Cc",
	}
	WidgetType_value = map[string]int32{
		"NULL":   0,
		"Custom": 1,
		"Cc":     2,
	}
)

func (x WidgetType) Enum() *WidgetType {
	p := new(WidgetType)
	*p = x
	return p
}

func (x WidgetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WidgetType) Descriptor() protoreflect.EnumDescriptor {
	return file_widgets_widgets_proto_enumTypes[0].Descriptor()
}

func (WidgetType) Type() protoreflect.EnumType {
	return &file_widgets_widgets_proto_enumTypes[0]
}

func (x WidgetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WidgetType.Descriptor instead.
func (WidgetType) EnumDescriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{0}
}

type GetWidgetsParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWidgetsParams) Reset() {
	*x = GetWidgetsParams{}
	mi := &file_widgets_widgets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWidgetsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWidgetsParams) ProtoMessage() {}

func (x *GetWidgetsParams) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWidgetsParams.ProtoReflect.Descriptor instead.
func (*GetWidgetsParams) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{0}
}

func (x *GetWidgetsParams) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWidgetsParams) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Widget struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Uuid      []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title     string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type      WidgetType             `protobuf:"varint,3,opt,name=type,proto3,enum=widgets.WidgetType" json:"type,omitempty"`
	Order     int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Widget_Cc
	Data          isWidget_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Widget) Reset() {
	*x = Widget{}
	mi := &file_widgets_widgets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Widget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Widget) ProtoMessage() {}

func (x *Widget) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Widget.ProtoReflect.Descriptor instead.
func (*Widget) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{1}
}

func (x *Widget) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Widget) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Widget) GetType() WidgetType {
	if x != nil {
		return x.Type
	}
	return WidgetType_NULL
}

func (x *Widget) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Widget) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Widget) GetData() isWidget_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Widget) GetCc() *WidgetListCc {
	if x != nil {
		if x, ok := x.Data.(*Widget_Cc); ok {
			return x.Cc
		}
	}
	return nil
}

type isWidget_Data interface {
	isWidget_Data()
}

type Widget_Cc struct {
	Cc *WidgetListCc `protobuf:"bytes,6,opt,name=cc,proto3,oneof"`
}

func (*Widget_Cc) isWidget_Data() {}

type WidgetListCc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WidgetCc            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetListCc) Reset() {
	*x = WidgetListCc{}
	mi := &file_widgets_widgets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetListCc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetListCc) ProtoMessage() {}

func (x *WidgetListCc) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetListCc.ProtoReflect.Descriptor instead.
func (*WidgetListCc) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{2}
}

func (x *WidgetListCc) GetItems() []*WidgetCc {
	if x != nil {
		return x.Items
	}
	return nil
}

type WidgetCc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinId        int32                  `protobuf:"varint,1,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetCc) Reset() {
	*x = WidgetCc{}
	mi := &file_widgets_widgets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetCc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetCc) ProtoMessage() {}

func (x *WidgetCc) ProtoReflect() protoreflect.Message {
	mi := &file_widgets_widgets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetCc.ProtoReflect.Descriptor instead.
func (*WidgetCc) Descriptor() ([]byte, []int) {
	return file_widgets_widgets_proto_rawDescGZIP(), []int{3}
}

func (x *WidgetCc) GetCoinId() int32 {
	if x != nil {
		return x.CoinId
	}
	return 0
}

func (x *WidgetCc) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_widgets_widgets_proto protoreflect.FileDescriptor

var file_widgets_widgets_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x2f, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x40, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x22, 0xdd, 0x01, 0x0a, 0x06, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73,
	0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x27, 0x0a, 0x02, 0x63, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x63, 0x48, 0x00, 0x52, 0x02, 0x63, 0x63, 0x42, 0x06, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x37, 0x0a, 0x0c, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x63, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x43, 0x63, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x39, 0x0a, 0x08,
	0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x43, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x69, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6f, 0x69, 0x6e, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x2a, 0x0a, 0x0a, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x43,
	0x63, 0x10, 0x02, 0x42, 0x17, 0x5a, 0x15, 0x78, 0x33, 0x61, 0x2e, 0x77, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x73, 0x3b, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_widgets_widgets_proto_rawDescOnce sync.Once
	file_widgets_widgets_proto_rawDescData []byte
)

func file_widgets_widgets_proto_rawDescGZIP() []byte {
	file_widgets_widgets_proto_rawDescOnce.Do(func() {
		file_widgets_widgets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_widgets_widgets_proto_rawDesc), len(file_widgets_widgets_proto_rawDesc)))
	})
	return file_widgets_widgets_proto_rawDescData
}

var file_widgets_widgets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_widgets_widgets_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_widgets_widgets_proto_goTypes = []any{
	(WidgetType)(0),               // 0: widgets.WidgetType
	(*GetWidgetsParams)(nil),      // 1: widgets.GetWidgetsParams
	(*Widget)(nil),                // 2: widgets.Widget
	(*WidgetListCc)(nil),          // 3: widgets.WidgetListCc
	(*WidgetCc)(nil),              // 4: widgets.WidgetCc
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_widgets_widgets_proto_depIdxs = []int32{
	0, // 0: widgets.Widget.type:type_name -> widgets.WidgetType
	5, // 1: widgets.Widget.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: widgets.Widget.cc:type_name -> widgets.WidgetListCc
	4, // 3: widgets.WidgetListCc.items:type_name -> widgets.WidgetCc
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_widgets_widgets_proto_init() }
func file_widgets_widgets_proto_init() {
	if File_widgets_widgets_proto != nil {
		return
	}
	file_widgets_widgets_proto_msgTypes[1].OneofWrappers = []any{
		(*Widget_Cc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_widgets_widgets_proto_rawDesc), len(file_widgets_widgets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_widgets_widgets_proto_goTypes,
		DependencyIndexes: file_widgets_widgets_proto_depIdxs,
		EnumInfos:         file_widgets_widgets_proto_enumTypes,
		MessageInfos:      file_widgets_widgets_proto_msgTypes,
	}.Build()
	File_widgets_widgets_proto = out.File
	file_widgets_widgets_proto_goTypes = nil
	file_widgets_widgets_proto_depIdxs = nil
}
